答：

终端输出内容：

```cpp
terminate called after throwing an instance of 'std::runtime_error'
  what():  b cannot be equal to 0.